/control/verbose 1

/geometry/source geometria_daniele.tg

/physics_lists/select QGSP_BERT_EMV
#/physics_lists/factory/addRadioactiveDecay
#/physics_lists/factory/addDecay

/run/initialize

/process/inactivate hIoni #ionizzazione adronica 
/process/inactivate eIoni #processi per e+ e e-
/process/inactivate eBrem
/process/inactivate msc
/process/inactivate phot #processi per i gamma
/process/inactivate compt
/process/inactivate conv

/geometry/test/run
/vis/geometry/list 

/gps/ene/type Pow
/gps/ene/min 1. GeV
/gps/ene/max 100. TeV
/gps/ene/alpha -2.7

/gps/direction 0 0 -1

/gps/pos/type Point
/gps/pos/centre 0. 0. 16000. m

/vis/open VRML2FILE
/vis/drawVolume
/vis/viewer/flush

/vis/scene/add/trajectories
/vis/scene/endOfEventAction accumulate 10

/vis/modeling/trajectories/create/drawByParticleID
/vis/modeling/trajectories/drawByParticleID-0/set mu- blue
/vis/modeling/trajectories/drawByParticleID-0/set mu+ blue
/vis/modeling/trajectories/drawByParticleID-0/set e- red
/vis/modeling/trajectories/drawByParticleID-0/set e+ red
/vis/modeling/trajectories/drawByParticleID-0/set gamma green
/vis/modeling/trajectories/drawByParticleID-0/set opticalphoton grey #green
/vis/modeling/trajectories/drawByParticleID-0/set proton cyan
/vis/modeling/trajectories/drawByParticleID-0/set neutron yellow
/vis/modeling/trajectories/drawByParticleID-0/set pi+ magenta
/vis/modeling/trajectories/drawByParticleID-0/set pi- magenta
/vis/modeling/trajectories/drawByParticleID-0/set kaon+ orange
/vis/modeling/trajectories/drawByParticleID-0/set kaon- orange
/vis/modeling/trajectories/drawByParticleID-0/set kaon0 orange
/vis/modeling/trajectories/drawByParticleID-0/set anti_kaon0 orange

/vis/filtering/trajectories/create/particleFilter
/vis/filtering/trajectories/particleFilter-0/add e-
/vis/filtering/trajectories/particleFilter-0/invert true

/tracking/verbose 1

/vis/disable
/gps/particle proton
#/run/beamOn 1


# turn off screen printing for fast simulation 
/tracking/verbose 0

# turn on progress report
/run/verbose 1
#/run/printProgress 1000

# start simulation

/gps/particle proton
/analysis/setFileName sciame
/run/beamOn 10000

